# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(max_length=225)),
                ('rating', models.FloatField()),
                ('city', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('tz', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('url', models.CharField(max_length=225)),
                ('elev', models.CharField(max_length=225)),
                ('direct_flights', models.CharField(max_length=225)),
            ],
        ),
    ]
